//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class availibility
    {
        public int idAvailability { get; set; }
        public byte isAvailable { get; set; }
        public string time { get; set; }
        public int idStaff { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
