//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cities
    {
        public cities()
        {
            this.restaurants = new HashSet<restaurants>();
            this.customer = new HashSet<customer>();
        }
    
        public int idCity { get; set; }
        public string city { get; set; }
        public string post_code { get; set; }
    
        public virtual ICollection<restaurants> restaurants { get; set; }
        public virtual ICollection<customer> customer { get; set; }
    }
}
