//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class credentials
    {
        public credentials()
        {
            this.customer = new HashSet<customer>();
        }
    
        public int idCredentials { get; set; }

        [DisplayName("User Name")] //changing the default "UserName" by putting a space (called in the view)
        [Required(ErrorMessage = "This field is required.")]
        public string username { get; set; }

        [DataType(DataType.Password)] //so what we type is hidden behind the usual "dots"
        [Required(ErrorMessage = "This field is required.")]
        public string password { get; set; }
        

        public string LoginErrorMessage { get; set; }

        public virtual ICollection<customer> customer { get; set; }
    }
}
