//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class credentials
    {
        public credentials()
        {
            this.customer = new HashSet<customer>();
        }
    
        public int idCredentials { get; set; }
        [Required]
        public string username { get; set; }
        [Required]
        public string password { get; set; }
    
        public virtual ICollection<customer> customer { get; set; }
    }
}
