//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dishes
    {
        public dishes()
        {
            this.dishes_order = new HashSet<dishes_order>();
        }
    
        public int idDishes { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public string status { get; set; }
        public int idRestaurant { get; set; }
    

        public virtual ICollection<dishes_order> dishes_order { get; set; }
        public virtual restaurants restaurants { get; set; }
    }
}
