//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dishes_order
    {
        public int idDishes { get; set; }
        public int idDishes_Order { get; set; }
        public int idOrder { get; set; }
    
        public virtual dishes dishes { get; set; }
        public virtual order order { get; set; }
    }
}
