//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GharbiThambirajahProject2Entities1 : DbContext
    {
        public GharbiThambirajahProject2Entities1()
            : base("name=GharbiThambirajahProject2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<availibility> availibility { get; set; }
        public DbSet<cities> cities { get; set; }
        public DbSet<credentials> credentials { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<delivery> delivery { get; set; }
        public DbSet<dishes> dishes { get; set; }
        public DbSet<dishes_order> dishes_order { get; set; }
        public DbSet<order> order { get; set; }
        public DbSet<restaurants> restaurants { get; set; }
        public DbSet<staff> staff { get; set; }
    }
}
