//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.dishes_order = new HashSet<dishes_order>();
        }
    
        public int idOrder { get; set; }
        public string status { get; set; }
        public string createdAt { get; set; }
        public int idCustomer { get; set; }
        public int idDelivery { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual delivery delivery { get; set; }
        public virtual ICollection<dishes_order> dishes_order { get; set; }
    }
}
